RELEASE_TYPE: patch

This release resolves :py:exc:`PermissionError` that come from
creating databases on inaccessible paths.
